### ISSUE TITLE
Prevent decimal number on the scale

### ISSUE THREAD

**Issue by kapso** [plivo/plivo-node#118]
Is there a way to prevent decimal numbers on the scale? I only would like to see whole numbers on the scale.

<img width="61" alt="Screen Shot 2019-04-05 at 2 58 22 PM" src="https://user-images.githubusercontent.com/344198/55658666-55b1f800-57b3-11e9-8b18-e51c31beb88c.png">

**Comment by nixonsam** [comment]
@kapso please elaborate a bit about what scale you are referring to so that we can check the same and assist you accordingly.

**Comment by nixonsam** [comment]
@kapso I'm closing this now, feel free to reach out to us or create a support ticket.
