### ISSUE TITLE
send email using plivo

### ISSUE THREAD

**Issue by deepak-carmatec** [plivo/plivo-node#142]
i am new to plivo....i want to send email when a user successfully register....in the backend we r using loopback.
please help me out.

**Comment by nixonsam** [comment]
@deepak-carmatec At Plivo, we provide Messaging & Voice APIs. Please go through our documentation to get started with the same. 

[Messaging API](https://www.plivo.com/docs/sms/)
[Voice API](https://www.plivo.com/docs/voice/)

I understand that your use-case is to send a notification when a new user is registering. You can use our messaging API to send an SMS once a user has been successfully registered.

Feel free to contact our [support team](https://support.plivo.com/support/home) in case of any concerns or queries. 

Thanks!
