### ISSUE TITLE
Promise error does not work

### ISSUE THREAD

**Issue by fgnm** [plivo/plivo-node#148]
Promise error content is empty when using catch block. This is a sample code:
```JavaScript
const plivo = require('plivo');
const client = new plivo.Client(CONF.plivo_auth_id, CONF.plivo_auth_token);

FUNC.sms = {};

FUNC.sms.send = function (controller, dest, text, cb) {
    client.messages.create(
        null,
        dest,
        text
    ).then(message_created => {
        cb(null, message_created);
    }, err => {
        cb(err, null);
    });

};
```
The `err` parameter is always empty. In this example I should get an error because I've not provided any `src` number.

**Comment by narayana-plivo** [comment]
@fgnm ,
Hi,
can you run this simple snippet and confirm , are you not getting error? .  When i ran, i have got the error message.

client.messages.create(
    null,
    '123444',
    '1122'
  ).then(message_created => {
    console.log("success")
  }, err => {
   console.log(err)
  });

Error: Neither of src or powerpack uuid present, either one is required

Source code:
https://github.com/plivo/plivo-node/blob/master/lib/resources/messages.js#L98
