### ISSUE TITLE
.get.conferences returns error when conference not found

### ISSUE THREAD

**Issue by kmuenze** [plivo/plivo-node#155]
.get.conferences returns error when conference not found

it should return no conference found instead of an error

**Comment by kmuenze** [comment]
This issue means all calls to get a conference need to be wrapped in a try/catch if you are using async/await like:

try{
  let x = await plivo.get.conferences("someConf");
} catch(e){
  let x = {
        "result":"no conference found"
  }
}

it seems better to just return no result rather than throw an error. 

Is this how all calls to get an entity work?

**Comment by nixonsam** [comment]
@kmuenze Hope, you got the list of functions and API where you can expect 404 when the resource is not found.

I'm closing this now, please reopen in case of any further queries. 

Thanks!
