### ISSUE TITLE
Inaccurate constructor TypeScript type

### ISSUE THREAD

**Issue by WesCossick** [plivo/plivo-node#173]
The TypeScript definition for the `Client` class ([this line of code](https://github.com/plivo/plivo-node/blob/master/types/rest/client.d.ts#L10)) is defined inaccurately. It indicates that the first two parameters, `authId` and `authToken`, are required. However, this is contrary to the [README](https://github.com/plivo/plivo-node/blob/master/README.md):

> We recommend that you store your credentials in the PLIVO_AUTH_ID and the PLIVO_AUTH_TOKEN environment variables, so as to avoid the possibility of accidentally committing them to source control. If you do this, you can initialise the client with no arguments and it will automatically fetch them from the environment variables:
> 
> ```js
> let plivo = require('plivo');
> let client = new plivo.Client();
> ```

**Comment by huzaif-plivo** [comment]
@Brando753 We have fixed this in our [latest release](https://github.com/plivo/plivo-node/releases/tag/4.14.1), please feel free to contact our [support team](https://support.plivo.com/hc/en-us) for any issues.
