### ISSUE TITLE
Bump up axios package to >=0.21.1

### ISSUE THREAD

**Issue by sreeteja06** [plivo/plivo-node#182]
Plivo has the following security issue, this can be fixed by updating the Axios package
High            Server-Side Request Forgery                                   

  Package         axios                                                         

  Patched in      >=0.21.1                                                      

  Dependency of   plivo                                                         

  Path            plivo > axios                                                 

  More info       https://npmjs.com/advisories/1594

**Comment by narayana-plivo** [comment]
@sreeteja06  https://github.com/plivo/plivo-node/pull/184 PR raised for same
