### ISSUE TITLE
Search functionality not working with country ISO.

### ISSUE THREAD

**Issue by antoniobologna** [plivo/plivo-node#188]
As per documentation at https://www.plivo.com/docs/numbers/api/phone-number#search-phone-numbers

the code specifies to use search method signature with 2 parameters: country_iso and optional parameters.

The first parameter is a string, which requires the country ISO (in my case 'US'), and the second parameter although it specifies that this is an optional parameter, it is still required:

`client.numbers.search`

![image](https://user-images.githubusercontent.com/37680779/121298597-c4220180-c8b9-11eb-94fa-f59b85d40ca4.png)

That is a problem, nevertheless right now the blocker I have is that I need to use this in order to search for numbers and provisioned them for my users, using the buy a number afterward, but still need the list that the search method generates, but it always throws me the error that I need the country iso.

This is the code I'm using:

```ts
const plivoClient = new PlivoClient(PLIVO_ID, PLIVO_TOKEN);

const phoneNumberList: SearchNumberResponse = await plivoClient.numbers.search('US', {
  pattern: `${areaCode}`,
  services: 'voice,sms,mms',
  limit: 10,
});
```

The error I'm getting:

```
error:   Error: Request failed with status code 400
    at createError (/Users/.../Projects/.../node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/.../Projects/.../node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/.../Projects/.../node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:467:12)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
{"api_id":"...","error":"Please provide country_iso to search for numbers."}
```

**Comment by huzaif-plivo** [comment]
@antoniobologna In our most recent Plivo node version [v4.17.1,](https://github.com/plivo/plivo-node/releases/tag/v4.17.1) we were unable to duplicate the issue. We believe you are using an older version of the Plivo node SDK. Could you please upgrade your Plivo node version and let us know if the error persists?

You can use the following commands to upgrade your Plivo node SDK.
`npm install plivo@latest` or `npm install plivo`

Feel free to contact our [support team](https://support.plivo.com/hc/en-us) if you require any additional assistance.

**Comment by antoniobologna** [comment]
Thank you @huzaif-plivo I have confirmed that the latest version fixes this issue.

**Comment by huzaif-plivo** [comment]
@antoniobologna Happy to help! 😊
