### ISSUE TITLE
Throwing an error "invalid country ISO".

### ISSUE THREAD

**Issue by Jaysojitra13** [plivo/plivo-node#201]
When I try to search the number based on country ISO, it is showing me the error like

```
Error: invalid country ISO
    at InvalidRequestError.PlivoRestError (/Users/jaysojitra/Documents/personal/node-test/node_modules/plivo/dist/utils/restException.js:18:118)
    at new InvalidRequestError (/Users/jaysojitra/Documents/personal/node-test/node_modules/plivo/dist/utils/exceptions.js:45:123)
    at /Users/jaysojitra/Documents/personal/node-test/node_modules/plivo/dist/rest/axios.js:284:22
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  status: 400,
  statusText: 'BAD REQUEST',
  apiID: 'e91eae67-eab8-11eb-a296-0242ac110001',
  moreInfo: '{"country_iso":{"country_iso":"US"}}
```

Here is my code

```
const plivo = require('plivo');

const client = new plivo.Client("<auth_id>", "<auth_token>");

client.numbers.search({
  country_iso: 'US',
}).then((res) => {
  console.log("123wer => ", res);
}).catch(err => {
  console.log("123 => ", err);
})
```

**Comment by huzaif-plivo** [comment]
@Jaysojitra13 The code snippet used appears to be incorrect, please try the code below with the latest version of [Plivo node](https://github.com/plivo/plivo-node/releases/tag/v4.20.1) SDK and let us know if you have any trouble. Information about attributes that can be passed along with this snippet can be found on this [page](https://www.plivo.com/docs/numbers/api/phone-number/#search-phone-numbers). You can also refer our example code snippets related to phone numbers [here](https://github.com/plivo/plivo-examples-node/blob/master/numbers/rent_unrent_numbers.js).

```
var plivo = require('plivo');

(function main() {
    'use strict';
    
   // If auth id and auth token are not specified, Plivo will fetch them from the environment variables.
    var client = new plivo.Client("<auth_id>","<auth_token>");
    client.numbers.search(
        "GB", // country iso
    ).then(function (response) {
        console.log(response);
    }, function (err) {
        console.error(err);
    });
})();
```
Feel free to contact our [support-team](https://support.plivo.com/hc/en-us) for any concerns.

**Comment by jay-edx** [comment]
Thanks, @huzaif-plivo for the quick support. I'll try this code and let you konw.
