### ISSUE TITLE
List recordings parameters ignored

### ISSUE THREAD

**Issue by brandtabbott** [plivo/plivo-node#207]
When trying to call `plivoClient.recordings.list({limit:1})` the API request seems to ignore the params and always returns 20 records.  Is this the correct usage?

In my use case I actually just want to filter by call_uuid but providing that wasn't working for me either.

I'm using the latest version of the library and most current node version (LTS).

**Comment by huzaif-plivo** [comment]
@brandtabbott The issue has been fixed in our [latest release](https://github.com/plivo/plivo-node/releases/tag/v4.22.1). Feel free to contact our [support-team](https://support.plivo.com/hc/en-us) for any concerns.
