### ISSUE TITLE
Bought phone number not getting assigned to passed appId

### ISSUE THREAD

**Issue by waynerobinson** [plivo/plivo-node#214]
When buying a new phone number and setting the appId to a valid value, the new phone number is being assigned to the default app. 

A subsequent update to assign the appId to the phone number works though.

The docs imply that it's possible to configure this during the buying process though.

https://github.com/plivo/plivo-node/blob/f3e6d9e3606eef6a74e1b228d2d4c9dce75e7b8a/lib/resources/numbers.js#L120

**Comment by huzaif-plivo** [comment]
@waynerobinson Thank you for the feedback. We have fixed this issue in our latest release((v4.23.1)[https://github.com/plivo/plivo-node/releases/tag/v4.23.1]), we request you to upgrade your Plivo node SDK version to fix the issue. In case of any queries, please feel free to contact our [support-team](support.plivo.com/hc/en-us).
