### ISSUE TITLE
Timeout on mass text message call

### ISSUE THREAD

**Issue by mathew2450** [plivo/plivo-node#227]
We received a timeout on the plivo mass text message api call. We have sent messages at this rate before with no issues. It was a bulk message with 1000 phone numbers. Here are is the error: 

`Error: Error: timeout of 5000ms exceeded at createError (/workspace/node_modules/plivo/node_modules/axios/lib/core/createError.js:16:15) at RedirectableRequest.handleRequestTimeout (/workspace/node_modules/plivo/node_modules/axios/lib/adapters/http.js:303:16) at RedirectableRequest.emit (events.js:314:20) at RedirectableRequest.EventEmitter.emit (domain.js:506:15) at Timeout.<anonymous> (/workspace/node_modules/plivo/node_modules/follow-redirects/index.js:164:12) at listOnTimeout (internal/timers.js:554:17) at processTimers (internal/timers.js:497:7) at /workspace/send-texts.js:275:27 at processTicksAndRejections (internal/process/task_queues.js:97:5)`

here is our call: 
`response = await client.messages.create(
                            {
                                'src': textGroup[0].src, //src
                                'dst': totalDstText, // dst
                                'text': textGroup[0].text, // text
                                'type': 'sms',
                                'method': "POST",
                                'url': deliveryReportMicroserviceURL
                            }
                        )`
totalDstText is the concatenated list of phone numbers.   We haven't sent a mass text like this in a while, and it looks like it might be related to your change on July 27th: 

`else if(typeof config.timeout === 'undefined'){
      options.timeout = 5000;
    }`
    
[https://github.com/plivo/plivo-node/pull/197/files](url)

**Comment by narayana-plivo** [comment]
@mathew2450 your right. When you wont specify timeout, default is set to 5000 second on above PR. (https://github.com/plivo/plivo-node/pull/197/files). 

you can set the max timeout like this 
```let client = new plivo.Client("xxx","xxxxx",{"timeout": 10000});``` in this case your setting 10000 timeout.

@nixonsam

**Comment by mathew2450** [comment]
Where is this in the documentation for sending sms? What is the maximum timeout allowed?

**Comment by narayana-plivo** [comment]
@huzaif-plivo Currently we don't have metrics about timeout. It depends on network call also.  Shall we remove the timeout for messaging now?

**Comment by narayana-plivo** [comment]
cc @abhineet-plivo

**Comment by abhineet-plivo** [comment]
Hey @mathew2450 will definitely fix this up from our side, in the meantime either you can split a bulk request into smaller destination number groups(maybe 500 each) or you make like to increase the timeout as suggested by @narayana-plivo

**Comment by huzaif-plivo** [comment]
@mathew2450 Thank you for the feedback! we have fixed this in our [latest version](https://github.com/plivo/plivo-node/releases/tag/v4.25.1) by excluding the timeout for messaging requests. Feel free to contact our [support team](https://support.plivo.com/hc/en-us) for any queries.
