### ISSUE TITLE
Uncaught exception: TypeError: Cannot read properties of undefined (reading 'status')

### ISSUE THREAD

**Issue by saltire** [plivo/plivo-node#229]
See issue https://github.com/plivo/plivo-node/issues/204. I just got this error again with v4.25.0. There are a few places in the `axios.js` file where a `reject` needs to be followed by a `return` or an `else` block to prevent accessing a property on an undefined `error.response`.

**Comment by narayana-plivo** [comment]
@huzaif-plivo  @saltire  https://github.com/plivo/plivo-node/pull/230

**Comment by huzaif-plivo** [comment]
@saltire Thank you for the feedback! We have fixed this in our [latest version](https://github.com/plivo/plivo-node/releases/tag/v4.25.1). Feel free to contact our [support team](https://support.plivo.com/hc/en-us) for any queries.
