### ISSUE TITLE
how to get status of an outgoing call?

### ISSUE THREAD

**Issue by pepe-keke** [plivo/plivo-node#248]
Im trying to get the status of an outgoing call, but I'm just getting in-progress status and i'm stuck in that how can i get the others aswell, like ringing, completed, failed etc??

           

            app.get('/make_call/', (req, res) => { 
                var r = plivo.Response();
    
                let call_uuid = req.param('CallUUID')
                let status = req.param('CallStatus')
    
                console.log("Call UUID:", call_uuid)
                console.log("Call Status:", status)
                
                res.writeHead(200, {'Content-Type': 'text/xml'});
                res.end(r.toXML());

            })

OUTPUT: 

           Call UUID: f6dcc5f3-aaf7-4ffa-b2b4-0fa3f643017a
           Call Status: in-progress
           Call UUID: undefined
           Call Status: undefined

**Comment by huzaif-plivo** [comment]
@pepe-keke This [document](https://www.plivo.com/docs/voice/use-cases/dial-status-reporting/node#xml-how-it-works) contains the information. If you have any further questions, please contact our [support-team](https://support.plivo.com/hc/en-us).
