### ISSUE TITLE
Typing change is incorrect for calls.create response

### ISSUE THREAD

**Issue by robertjustjones** [plivo/plivo-node#252]
The change made in #213  has requestUuid returning as a string[], but it is string. I don't see any discussion on why this was changed, but it is incorrect for v4.32.0.
```
 const callResponse = await plivoClient.calls.create( srcPhone, dstPhone, url );
```
callResponse is
```
{
  "apiId": "da50dd52-e285-11ec-a9de-xxxx",
  "message": "call queued",
  "requestUuid": "142e08a9-475d-47c1-853a-xxxx"
}
```

**Comment by huzaif-plivo** [comment]
@robertjustjones Thank you for bringing this to our attention. Depending on the type of request, the parameter requestUuid can be `Array<string>` or `string`. If the call is to a single destination number, our response is as follows.

```shell
CreateCallResponse {
  apiId: '31bba055-e65f-11ec-bfda-0242ac110008',
  message: 'call fired',
  requestUuid: 'e5e13378-26bc-48f0-8494-4893746545b7'
}
```

However, if the call is to multiple destinations, i.e. a [bulk call](https://www.plivo.com/docs/voice/use-cases/make-bulk-calls/node#xml-make-an-outbound-call-to-multiple-numbers), the response is as follows.

```shell
CreateCallResponse {
  apiId: '39f42949-e65f-11ec-95f3-0242ac110002',
  message: 'calls fired',
  requestUuid: [
    'bdbf278e-ae49-4035-b68e-8a0087bb243c',
    '8db669c3-f888-4a53-acce-d18638161ee5'
  ]
}
```
I've created a [PR](https://github.com/plivo/plivo-node/pull/253) that should resolve this issue. If you have any further questions, please contact our [support team](https://support.plivo.com/hc/en-us).
