### ISSUE TITLE
Need a help on forwarding calls:

### ISSUE THREAD

**Issue by NurdinDev** [plivo/plivo-node#262]
How to build a lister to catch incoming calls and forward them to a certain phone number?

**Comment by huzaif-plivo** [comment]
@NurdinDev When there is an incoming call, you may create a <[Conference Room](https://www.plivo.com/docs/voice/xml/conference/)> and aggregate all incoming callers. For each of these calls, Plivo produces a unique call uuid. You may use a different service to keep lists of your calls, and then use the Plivo API to [transfer](https://www.plivo.com/docs/voice/api/call#transfer-a-call) your call to the number you want to forward using a <[Dial XML](https://www.plivo.com/docs/voice/xml/dial#dialstatus-reporting)>. I hope this helps to solve your question. If you have any questions concerning the implementation, please feel free to contact our [support-team](https://support.plivo.com/hc/en-us).

**Comment by NurdinDev** [comment]
Thank you for your help, I’m checking the doc and I come across [Call Forwarding](https://www.plivo.com/docs/voice/use-cases/call-forwarding/node)

Does that help instead of the conference room?

**Comment by huzaif-plivo** [comment]
I'm glad that you came across the document. Yes, it does!
