### ISSUE TITLE
Console.log on listing all endpoints

### ISSUE THREAD

**Issue by PhilippeLx** [plivo/plivo-node#268]
Theres a console.log left in the listing endpoints function. Its makes a big spam in the node console.
<img width="484" alt="image" src="https://user-images.githubusercontent.com/82614932/197199186-afc31f7a-8b2c-4d1b-911d-fa19f5d06921.png">

**Comment by narayana-plivo** [comment]
@PhilippeLx we addressed the console.log. closing the issue.
