### ISSUE TITLE
The API Crashes Server in Some Cases.

### ISSUE THREAD

**Issue by beneloper** [plivo/plivo-node#27]
On line 76, there are cases where response is null which causes javascript error.  This has crashed our server few times.
```
     75   Request.post(request_options, function (error, response, body) {
     76      if (response.statusCode != 201) {
     77          err = new PlivoError(error);
     78      }
     79      callback(response.statusCode, body);
     80  });
```

**Comment by sandeepraju** [comment]
@beneloper can you tell us which api's response causes this issue?

**Comment by beneloper** [comment]
send_message()
```
            var p = plivo.RestAPI(configs.plivo),
                plivoParams = {
                    'src': configs.PLIVO_SMS_SRC, // Caller Id
                    'dst' : phoneNumber, // User Number to Call
                    'text': msg,
                    'type': "sms"
                };
            p.**send_message**(plivoParams, function (status, response) {
                log.info('API status: %d, Response: %j', status, response);
                callback(null, response);
            });
 ```

**Comment by sandeepraju** [comment]
@beneloper I tried this out and some more variants (like bulk sms, invalid params, etc). Worked fine to me. If you continue facing issues, please create a support ticket on your account dashboard providing request params, api_id, message_uuid.

**Comment by beneloper** [comment]
We've used this for 5 months and it crashed few times so it's not easy just to try few times.  Anyway, I saw someone fixed the issue in the latest version (lines 77-79 added).  It's good practice not to assume that the variables returned always have values, especially the module used (request) is from third party.
```      
76  Request.post(request_options, function (error, response, body) {
77       if (error || !response) {             
78              return callback(500, body)
79       }
80       if (response.statusCode != 201) {
81           err = new PlivoError(error);
82       }
83       callback(response.statusCode, body);
84  });
```
