### ISSUE TITLE
Unable to send MMS without text provided

### ISSUE THREAD

**Issue by kirick1** [plivo/plivo-node#289]
Hello, team. There is a small issue with validation in messages.create method in case of sending MMS message, error message "Missing mandatory field: text", text is required parameter, empty string is not valid, looks like issue with validation here https://github.com/plivo/plivo-node/blob/2259f77ceb187209aef8fc654a07ec7f1a792e7d/lib/resources/messages.js#L218

**Comment by narayana-plivo** [comment]
@kirick1 we have removed the mandatory param. But as per method signature, you have to provide empty string for text param.

**Comment by kirick1** [comment]
Thanks!
