### ISSUE TITLE
Client Options is typed as string instead of an object

### ISSUE THREAD

**Issue by schmidlidev** [plivo/plivo-node#328]
The [API documentation](https://www.plivo.com/docs/sms/api/overview/) says that an options object can be passed to the client:
```ts
var plivo = require('plivo');
let options = {
	'timeout': 50000, //ms
	'host': 'https://proxyurl',
	'port': 'proxyport',
	auth: {
		username: 'my-user',
		password: 'my-password'
	}
}

var client = new plivo.Client("<auth_id>", "<auth_token>", options);
```

However, in typescript `options` is typed as `string` rather than an object (or even just `any`). 
https://github.com/plivo/plivo-node/blob/master/types/rest/client.d.ts#L10

**Comment by huzaif-plivo** [comment]
This is fixed in this [PR](https://github.com/plivo/plivo-node/pull/329/files) by @narayana-plivo
