### ISSUE TITLE
Weird characters on SMS

### ISSUE THREAD

**Issue by reyhansofian** [plivo/plivo-node#42]
Why there are weird characters whenever I received an SMS? Please see attachment below

![screen shot 2016-06-28 at 10 07 26](https://cloud.githubusercontent.com/assets/5353857/16402731/ef5bd24a-3d18-11e6-98d4-d76166f9d636.png)

**Comment by cachrisman** [comment]
can you share the code you use to send the message?

**Comment by reyhansofian** [comment]
here's my code

```
  var number = input.phone.replace(/^0/, "62");
  var message = "Order telah diterima, mohon lakukan pembayaran Rp" + input.cost + " ke rekening " + paymentText + " untuk memastikan order diproses, Terima Kasih.Tabook Indonesia";
  var params = {
    'src': 'tabook', // Sender's phone number with country code
    'dst': number, // Receiver's phone Number with country code
    'text': message, // Your SMS Text Message - English
    'method': "GET" // The method used to call the url
  };
  // Prints the complete response
  p.send_message(params, function(status, response) {
    console.log('Status: ', status);
    console.log('API Response:\n', response);
    console.log('Message UUID:\n', response['message_uuid']);
    console.log('Api ID:\n', response['api_id']);
  });
```

**Comment by reyhansofian** [comment]
even after doing some debugging, there's nothing wrongs before I send the message

```
{ src: 'tabook',
  dst: xxxxx,
  text: 'Order telah diterima, mohon lakukan pembayaran Rpxxxx ke rekening (0900364393 a/n Villa Dwi Erwanto) untuk memastikan order diproses, Terima Kasih.Tabook Indonesia',
  method: 'GET' }
```

**Comment by cachrisman** [comment]
does this only happen when sending to Indonesia? If you send to a US number does it still happen? I don't see anything in your code that would cause this to happen. Probably best to [submit a support ticket](https://manage.plivo.com/contact/support/) and let the support team help you.

**Comment by reyhansofian** [comment]
@cachrisman I'm not sure if it's a number issue (since my team didn't have any client outside Indonesia). I think it's because my message is more than 160 characters (long sms). For now, I'm cutting the message so it's not categorized as long sms as workaround. I've submitted support ticket yesterday, but there's still no answer. 

Thanks for your response 😄
