### ISSUE TITLE
global leak error with mocha unit test

### ISSUE THREAD

**Issue by AmicoJoules** [plivo/plivo-node#66]
Our mocha unit test are failing after upgrading to `plivo` version 4.0.0 with error

`Error: global leak detected: Parser`

`node` version is 8
`mocha` version is 5

**Comment by plivo-sdks** [comment]
@AmicoJoules This seems to be a leak from the uri-parser module that we are using in the SDK. Can you ignore `Parser` in your mocha global leak check?

**Comment by AmicoJoules** [comment]
@plivo-sdks can't do, it goes against company policy. I have already raised an issue in the `uri-parser` repository https://github.com/goulash1971/uri-parser/issues/1 , it would be great if you could add a supporting comment, thanks

**Comment by acrodrig** [comment]
Hi, this is a priority for us. Can you help? We cannot run tests on Plivo because of this. If the library you use has leaks, you should switch to another library.

**Comment by AmicoJoules** [comment]
To anyone having this error, you can use `package.lock` to override the version of the dependency that the plivo library is using
