### ISSUE TITLE
Sending message to a non verified phone number

### ISSUE THREAD

**Issue by ed-zm** [plivo/plivo-node#68]
Hi, I am trying to send a message to a not verified phone number in plivo, I got an error that the destination number needs to be verified, however there is no API to verify the numbers. It is useless because I need to send sms to any phone number registered in my db. Any Ideas? thanks

**Comment by ed-zm** [comment]
I contacted the support and I had to upgrade my account to be able to do this. Solved

**Comment by ShreeForcebolt** [comment]
Hi @ed-zm 
How You had resolved this issue because I am facing same problem ?
