### ISSUE TITLE
Optional parmas in creating message

### ISSUE THREAD

**Issue by chderen** [plivo/plivo-node#70]
Hi,
I tried to send sms with additional param (log = false)
i found that the value should be string. 
it's not clear in the documentation.

Thanks

`client.messages.create(
                src,
                dst,
                msg, 
                {
                    log: "false"
                }
            ).then(function (message_created) {
                console.log(message_created);
            }).catch(function (err) {
                 console.error(err);
           });`

**Comment by nixonsam** [comment]
@chderen this is fixed and docs are available [here](https://www.plivo.com/docs/sms/detailed-reference/api/message/send-a-message/)

We are closing this now, feel free to contact our support team in case of any further concerns. 

Thank you!
