### ISSUE TITLE
Typescript type definitions

### ISSUE THREAD

**Issue by from-nibly** [plivo/plivo-node#72]
Is adding typescript type definitions for the plivo client on the radar for this project?

**Comment by matheo** [comment]
@plivo-sdks please, these typings are more than required these days to be considered a top quality product. Thanks!

**Comment by katwekibs** [comment]
Any idea where can i get typescript type definitions for plivo?

**Comment by dgobaud** [comment]
@plivo-sdks yes types please! need to add to here https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by nixonsam** [comment]
@dgobaud @katwekibs @matheo @from-nibly We are working on this. We will keep you informed once typescript support is added. 
We appreciate your patience & support!

**Comment by joerozek** [comment]
@nixonsam  any update on this?

**Comment by ahmednaser94** [comment]
@nixonsam any updates for this? because i can't use it inside typescript at all

**Comment by focux** [comment]
More than two years later and it still doesn't have type definitions.

**Comment by nixonsam** [comment]
@focux @joerozek @dgobaud @katwekibs  @matheo @from-nibly We've added Typescript support to our SDK, You can check https://github.com/plivo/plivo-node/releases/tag/v4.13.0. Thanks!
