### ISSUE TITLE
Latest version: v4.0.0 or v0.4.2

### ISSUE THREAD

**Issue by andenis** [plivo/plivo-node#73]
What is the latest version? Ref: Releases

npm install -> v4.0.0
plivo-node -> last release: v0.4.2

**Comment by patelravi** [comment]
Hi Andenis,

Sorry for delayed reponse.
You can alwyas check latest release on npm website.
Link is given below.
https://www.npmjs.com/package/plivo-node

Regards,
Ravi

**Comment by sseppola** [comment]
There are two npm packages linked to this repo:
https://www.npmjs.com/package/plivo (last publish 1 month ago, v4.0.5)
https://www.npmjs.com/package/plivo-node (last publish 5 years ago, v0.2.5)

**Comment by ClickSimply** [comment]
Looks like `plivo-node` is their legacy implantation.

Go [here](https://api-reference.plivo.com/) and select "legacy" and "node" at the top right, you'll get the api for `plivo-node`.  If you select "latest" in the top right you get the API for the current library, `plivo`.
