### ISSUE TITLE
validateSignature does not account for port numbers in urls.

### ISSUE THREAD

**Issue by adjenks** [plivo/plivo-node#83]
When executing plivo.validateSignature() if the URL contains a port number the function does not output true when it should because the value from the X-Plivo-Signature-V2 sent from the server DOES account for the port number but this function pulls apart the url and puts it back together for some reason.
I had to write my own function to fix this, basically throwing away the url parsing lines and using the url as is so that it would include the port number.
So my code looks like this:
```
function validateSignature(uri, nonce, signature, auth_token) {
  nonce = utf8.encode(nonce);
  signature = utf8.encode(signature);
  auth_token = utf8.encode(auth_token);
  uri = utf8.encode(uri);
  let hmac = crypto.createHmac('sha256', auth_token);
  let hmacBytes = base64.decode(hmac.update(uri+nonce).digest('base64'));
  let authentication_string = base64.encode(hmacBytes);
  return authentication_string == signature;
}
```
An example of a url that does not work is `https://www.example.com:4433/examplepath`

**Comment by nixonsam** [comment]
@adjenks This is fixed and released(https://github.com/plivo/plivo-node/releases/tag/v4.1.3).
