### ISSUE TITLE
security functions are not in the documentation anywhere

### ISSUE THREAD

**Issue by adjenks** [plivo/plivo-node#84]
The API docs on the Plivo site take you here, and github links back to the Plivo site.
Please document the security functions somewhere.

**Comment by nixonsam** [comment]
@adjenks you can check [here](https://www.plivo.com/legal/tos/) for general security and terms & use.
Also, regarding the security for transactions between your servers and Plivo while integrating with Plivo, you can check [here](https://api-reference.plivo.com/latest/node/plivo-xml/request/validation).

If you still have any concerns or queries, please feel free to create a support ticket and we would help you accordingly.

Thank you.

**Comment by adjenks** [comment]
@nixonsam 
I wanted documentation for this file and its functions:
https://github.com/plivo/plivo-node/blob/master/lib/utils/security.js

**Comment by adjenks** [comment]
Can I find that somewhere? Aside from just reading the code? Example usage?
