### ISSUE TITLE
How to retrieve pricing?

### ISSUE THREAD

**Issue by Extarys** [plivo/plivo-node#89]
Since the CSV the website provides, the information on the website and what I'm being billed contradict themselves, I want to setup a price monitoring tool so I know every time a price change happens.

```
var client = new plivo.Client(
      config.providers.plivo.auth_id,
      config.providers.plivo.auth_token
    )
    client.Pricings().then( // pricing, pricings, Pricing, Pricings...
      function(response) {
        // console.log(response)
        reply.send(response)
      },
      function(err) {
        console.error(err)
      }
    )
```

How can I access the price list from the API? I found the file corresponding to it, but I don't know how to access it.

Thanks

**Comment by patelravi** [comment]
Hi Extarys,

Sorry for delayed reponse.

You will need to pass country code for which you want to retrieve pricing.
Also i think the client.pricing is in camel case, you have written client.Pricing in pascal case(P capital).

Following snippet might help you.

`client.pricings.get('US')
  .then(function (price) {
    console.log("\n============ get ===========\n", price)
  })
  .catch(function (response) {
    console.log("\n============ Error :: ===========\n", response);
  });
`
Let me know if you still facing issue.

**Comment by nixonsam** [comment]
@Extarys we are closing this case now, feel free to create a support ticket in case you need any further assistance or in case of any queries. 

Thank you!
